services:
  localstack:
    container_name: aws-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - SERVICES=s3,sqs
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
    healthcheck:
      test:
        "
          curl -X 'GET' \
            'http://localhost.localstack.cloud:4566/_localstack/health' \
            -H 'accept: application/json'
        "