spring:
  application:
    name: localstack
  docker:
    compose:
      enabled: true
  cloud:
    aws:
      sqs:
        enabled: true
        endpoint: http://localhost:4566
        region: us-east-1
